# logic/dev_present.py
# Tempat khusus untuk data frame animasi (Developer Corner).

KAOMOJI_FRAMES = [
    # Scene 1 & 2: Intro & Walk
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        " ( ´ ▽ ` )ﾉ                          ",
        "    \\|/                              ",
        "     |                               ",
        "    / \\                              ",
        "                                     ",
    ], 0.3),
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        "    ( ´ ▽ ` )ﾉ                       ",
        "       \\|                            ",
        "        |                            ",
        "       /|                            ",
        "                                     ",
    ], 0.3),
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        "       ( ´ ▽ ` )ﾉ                    ",
        "          \\|/                        ",
        "           |                         ",
        "          / \\                        ",
        "                                     ",
    ], 0.3),
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        "          ( ´ ▽ ` )ﾉ                 ",
        "             \\|                      ",
        "              |                      ",
        "             /|                      ",
        "                                     ",
    ], 0.3),
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        "             ( ´ ▽ ` )ﾉ              ",
        "                \\|/                  ",
        "                 |                   ",
        "                / \\                  ",
        "                                     ",
    ], 0.3),
    
    # Scene 3: Menyapa
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        "                ( ´ ▽ ` )/           ",
        "                   \\|                ",
        "                    |                ",
        "                   / \\               ",
        "                                     ",
    ], 0.4),
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        "                ( ´ ▽ ` )ﾉ           ",
        "                   \\|/               ",
        "                    |                ",
        "                   / \\               ",
        "                                     ",
    ], 0.4),

    # Scene 4: Ambil Kamera
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        "                ( >_< )              ",
        "                 >| [◉]              ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.5),
    ([
        "                                     ",
        "                                     ",
        "                                     ",
        "                ( >_• )> [◉]         ",
        "                  |                  ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.6),

    # Scene 5: Foto & Flash
    ([
        "                                     ",
        "                *CLICK!*             ",
        "                                     ",
        "                ( >_• )> [◉]         ",
        "                  |                  ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.2),
    ([
        "+-----------------------------------+",
        "|                                   |",
        "|              FLASH                |",
        "|                                   |",
        "+-----------------------------------+",
        "                                     ",
        "                                     ",
        "                                     ",
    ], 0.15),

    # Scene 6: Masalah
    ([
        "    Camera Storage:                  ",
        "    [ DSC_0001.JPG ]                 ",
        "                                     ",
        "                (・_・;)              ",
        "                  |/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.8),
    ([
        "    Camera Storage:                  ",
        "    [ DSC_0001.JPG ]                 ",
        "    [ DSC_0001.JPG ]                 ",
        "                (・_・;) Wait...      ",
        "                  |/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 1.2),

    # Scene 7: Panik
    ([
        "    !!! OVERWRITE WARNING !!!        ",
        "    Duplicate filename detected!     ",
        "                                     ",
        "                ( ≧Д≦)               ",
        "                 \\|/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.4),
    ([
        "    !!! DUPLICATE FILE !!!           ",
        "    Duplicate filename detected!     ",
        "                                     ",
        "                ( ≧Д≦)               ",
        "                 /|\\                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.4),
    ([
        "    !!! OVERWRITE WARNING !!!        ",
        "    Duplicate filename detected!     ",
        "                                     ",
        "                ( ≧Д≦)               ",
        "                 \\|/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.4),

    # Scene 8: Shot Sentinel Aktif
    ([
        "    Initializing Shot Sentinel...    ",
        "    [██░░░░░░]                       ",
        "                                     ",
        "                ( •̀ ω •́ )✧             ",
        "                 \\|/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.5),
    ([
        "    Initializing Shot Sentinel...    ",
        "    [█████░░░]                       ",
        "                                     ",
        "                ( •̀ ω •́ )✧             ",
        "                 \\|/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.5),
    ([
        "    Initializing Shot Sentinel...    ",
        "    [████████]                       ",
        "                                     ",
        "                ( •̀ ω •́ )✧             ",
        "                 \\|/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 0.5),

    # Scene 9: Proses Berhasil
    ([
        "    Renaming...                      ",
        "    [D3300]2026-07-09_0001.JPG       ",
        "                                     ",
        "                ( ^ω^)b              ",
        "                  |/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 1.0),
    ([
        "    Renaming...                      ",
        "    [D3300]2026-07-09_0001.JPG       ",
        "    ✓ Rename Successful              ",
        "                ( ^ω^)b              ",
        "                  |/                 ",
        "                  |                  ",
        "                 / \\                 ",
        "                                     ",
    ], 1.5),

    # Scene 10: Ending
    ([
        "====================================================",
        "              SHOT SENTINEL",
        "             Protect Your Media",
        "====================================================",
        "",
        "✓ File Protected",
        "✓ Rename Completed",
        "✓ Metadata Preserved",
        "",
        "Press any key to return..."
    ], 0.0)
]
